version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - setup_remote_docker:
          version: docker24
      - checkout
      - run:
          name: Update npm
          command: "sudo npm install -g npm@latest"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install Jest
          command: npm install jest
      - run:
          name: Run tests and generate coverage
          command: |
            mkdir -p test-results
            npm test -- --watchAll=false --coverage --outputFile=test-results/jest.xml --json --useStderr
      - run:
          name: Upload coverage to Code Climate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
            ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info
            ./cc-test-reporter upload-coverage
            ./cc-test-reporter after-build --exit-code $?
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage
          destination: coverage

workflows:
  test_workflow:
    jobs:
      - test
